dashboard/urls.py
from django.urls import path

from .views import main, users, profile, schools, teams, invitations

app_name = 'dashboard'

urlpatterns = [
    path('', main.IndexView.as_view(), name='index'),
    path('users/admins/', users.UserAdminsListView.as_view(), name='users-list-admins'),
    path('users/admins/new/', users.CreateUserAdminView.as_view(), name='users-admins-new'),
    path('users/organizers/', users.UserOrganizersListView.as_view(), name='users-list-organizers'),
    path('users/organizers/new/', users.CreateUserOrganizerView.as_view(), name='users-organizers-new'),
    path('users/students/', users.UserStudentsListView.as_view(), name='users-list-students'),
    path('users/guardians/', users.UserGuardiansListView.as_view(), name='users-list-guardians'),
    path('users/<int:pk>/', users.UserDetailView.as_view(), name='users-detail'),
    path('users/<int:pk>/edit/', users.UserUpdateView.as_view(), name='users-edit'),
    path('users/<int:pk>/delete/', users.UserDeleteView.as_view(), name='users-delete'),
    path('profile/', profile.ProfileDetailView.as_view(), name='profile-detail'),
    path('profile/edit/', profile.ProfileUpdateView.as_view(), name='profile-edit'),
    path('profile/delete/', profile.ProfileDeleteView.as_view(), name='profile-delete'),
    path('schools/', schools.SchoolsListView.as_view(), name='schools-list'),
    path('schools/type/<int:type>/', schools.SchoolsListView.as_view(), name='schools-list-type'),
    path('schools/my-schools/', schools.SchoolsGuardianListView.as_view(), name='schools-guardian-list'),
    path('schools/my-schools/edit/', schools.SchoolsGuardianUpdateView.as_view(), name='schools-guardian-edit'),
    path('schools/new/', schools.SchoolsCreateView.as_view(), name='schools-new'),
    path('schools/<int:pk>/', schools.SchoolsDetailView.as_view(), name='schools-detail'),
    path('schools/<int:pk>/edit/', schools.SchoolsUpdateView.as_view(), name='schools-edit'),
    path('schools/<int:pk>/delete/', schools.SchoolsDeleteView.as_view(), name='schools-delete'),
    path('teams/', teams.TeamsListView.as_view(), name='teams-list'),
    path('teams/new/', teams.TeamsCreateView.as_view(), name='teams-new'),
    path('teams/<int:pk>/', teams.TeamsDetailView.as_view(), name='teams-detail'),
    path('teams/<int:pk>/edit/', teams.TeamsUpdateView.as_view(), name='teams-edit'),
    path('teams/<int:pk>/delete/', teams.TeamsDeleteView.as_view(), name='teams-delete'),
    path('teams/<int:pk>/leader/add/', teams.TeamsLeaderConnectView.as_view(), name='teams-leader-new'),
    path('teams/<int:team_id>/leader/<int:pk>/edit/', teams.TeamsLeaderUpdateView.as_view(), name='teams-leader-edit'),
    path('teams/<int:pk>/leader/delete/', teams.TeamsLeaderDisconnectView.as_view(), name='teams-leader-delete'),
    path('teams/<int:pk>/members/new/', teams.TeamsMembersCreateView.as_view(), name='teams-members-new'),
    path('teams/members/<int:pk>/edit/', teams.TeamsMembersUpdateView.as_view(), name='teams-members-edit'),
    path('teams/members/<int:pk>/delete/', teams.TeamsMembersDeleteView.as_view(), name='teams-members-delete'),
    path('teams/<int:team_id>/file/<int:pk>/delete/', teams.TeamsFileDeleteView.as_view(), name='teams-file-delete'),
    path('teams/my/', teams.TeamsGuardianView.as_view(), name='teams-guardian-list'),
    path('teams/<int:pk>/disconnect/', teams.TeamsGuardianDisconnectView.as_view(), name='teams-guardian-disconnect'),
    path('invitations/', invitations.InvitationListView.as_view(), name='invitations-list'),
    path('invitations/<int:pk>/accept/', invitations.InvitationEditView.as_view(), name='invitations-edit-accept', kwargs={'accept': True}),
    path('invitations/<int:pk>/not-accept/', invitations.InvitationEditView.as_view(), name='invitations-edit-not-accept',  kwargs={'accept': False}),
    path('invitations/available-guardians/', invitations.InvitationsAvailableGuardiansListView.as_view(), name='invitations-available-guardians-list'),
    path('invitations/available-teams/', invitations.InvitationsAvailableTeamsListView.as_view(), name='invitations-available-teams-list'),
    path('invitations/invite/', invitations.InvitationCreateView.as_view(), name='invitations-invite'),
    path('invitations/invite-cancel/', invitations.InvitationCancelView.as_view(), name='invitations-invite-cancel'),
]

scolarctosapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('dashboard/', include('dashboard.urls')),
]

handler403 = 'dashboard.views.main.error_403'

dashboard/models/invitation.py
from django.db import models
from django.utils import timezone
from users.models import CustomUser as User
from dashboard.validators import validate_student_guardian

class InvitationNoneAcceptedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(accepted__isnull=True)
    
class Invitation(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender', validators=[validate_student_guardian])
    recipient = models.ForeignKey(User, on_delete=models.CASCADE, related_name='recipient', validators=[validate_student_guardian])
    accepted = models.BooleanField(blank=True, null=True, default=None) 
    created = models.DateField(default=timezone.now)

    objects = models.Manager()
    accepted_none_objects = InvitationNoneAcceptedManager()

    def __str__(self):
        return f'From: {self.sender.email} | To: {self.recipient.email} | Accepted: {self.accepted}'
    
    def get_guardian(self):
        if self.sender.is_guardian():
            return self.sender
        elif self.recipient.is_guardian():
            return self.recipient
    
    def get_student(self):
        if self.sender.is_student():
            return self.sender
        elif self.recipient.is_student():
            return self.recipient

    def get_team(self):
        leader = self.get_student()
        return leader.team_set.first()

dashboard/models/team.py
import os
from django.db import models
from django.utils import timezone
from users.models import CustomUser as User
from dashboard.models.school import School
from dashboard.models.team_guardian import TeamGuardian
from files.models import File

class Team(models.Model):
    MAX_MEMBERS = 3
    MAX_FILES = 5

    name = models.CharField(max_length=63, unique=True)
    description = models.TextField(blank=True)
    leader = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    team_guardian = models.ForeignKey(TeamGuardian, on_delete=models.SET_NULL, null=True, blank=True)
    team_members = models.ManyToManyField(
        User, 
        null=True, 
        blank=True, 
        related_name="team_members", 
        related_query_name="team_member",
        )
    school = models.ForeignKey(School, on_delete=models.SET_NULL, null=True, blank=True)
    editable = models.BooleanField(default=True)
    files = models.ManyToManyField(
        File, 
        null=True, 
        blank=True, 
        related_name="teams",
    )
    added_date = models.DateField(default=timezone.now)

    def __str__(self):
        return f'Name: {self.name} | Desc: {self.description} | Leader: {self.leader} | Guardian: {self.team_guardian} | School: {self.school} | Date: {self.added_date}'
    
    def delete(self, **kwargs):
        self.team_members.all().delete()
        # Must delete each file separately
        if self.files.exists():
            first_file = self.files.first()
            files_dir = first_file.path.path
            files_dir = files_dir.replace(first_file.name, '')
            for file in self.files.all():
                file.delete()
            os.rmdir(files_dir)
        return super().delete(**kwargs)

dashboard/models/team_guardian.py
from django.db import models
from users.models import CustomUser as User
from files.models import File

class TeamGuardian(models.Model):
    guardian = models.ForeignKey(User, on_delete=models.CASCADE)
    confirmation = models.BooleanField(default=False)
    confirmation_file = models.ForeignKey(File, on_delete=models.SET_NULL, null=True, blank=True)
    
    def __str__(self):
        return f'Guardian: {self.guardian} | Confirmation status: {self.confirmation} | Confirmation file: {self.confirmation_file}'

dashboard/models/team_tutor.py
from django.db import models
from users.models import CustomUser as User
from files.models import File

class TeamTutor(models.Model):
    tutor = models.ForeignKey(User, on_delete=models.CASCADE)
    confirmation = models.BooleanField(default=False)
    confirmation_file = models.ForeignKey(File, on_delete=models.CASCADE, null=True, blank=True)
    
    def __str__(self):
        return f'Tutor: {self.tutor} | Confirmation status: {self.confirmation} | Confirmation file: {self.confirmation_file}'

dashboard/views/invitations.py
import json
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import HttpResponseRedirect, HttpResponseBadRequest, JsonResponse
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic.list import ListView
from django.views.generic import CreateView, UpdateView
from django.views import View


from users.models import CustomUser
from dashboard.models import Team, Invitation, TeamGuardian

'''
### Invitations Views
'''

@method_decorator(login_required, name='dispatch')
class InvitationsAvailableGuardiansListView(PermissionRequiredMixin, ListView):
    context_object_name = 'guardians'
    template_name = 'dashboard/invitations/available-guardians-list.html'

    def dispatch(self, request, *args, **kwargs):
        self.leader = self.request.user
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        # Find all guardians connected to same school as user's team school
        # Guardian can connect with many teams
        leader_school = self.leader.team_set.first().school
        leader_received_invitations = self.leader.recipient.filter(accepted__isnull=True)
        return leader_school.guardians.exclude(sender__in=leader_received_invitations)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_name'] = 'Opiekunowie z Twojej szkoły'
        for guardian in context['guardians']:
            if guardian.recipient.filter(sender=self.leader).filter(accepted=None).exists():
                guardian.invited = True
        return context
    
    def has_permission(self):
        if self.leader.user_type == CustomUser.STUDENT and self.leader.team_set.exists() and self.leader.team_set.first().team_guardian is None:
            return True
        return False
    
@method_decorator(login_required, name='dispatch')
class InvitationsAvailableTeamsListView(PermissionRequiredMixin, ListView):
    context_object_name = 'teams'
    template_name = 'dashboard/invitations/available-teams-list.html'

    def dispatch(self, request, *args, **kwargs):
        self.guardian = self.request.user
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        # Find all teams connected to same school as guardian's schools
        # Team can connect only one guardian
        guardian_schools = self.guardian.schools.all()
        guardian_received_invitations = self.guardian.recipient.filter(accepted=None)
        teams = Team.objects.filter(
            school__in=guardian_schools, 
            team_guardian__isnull=True, 
            leader__isnull=False
            ).exclude(leader__sender__in=guardian_received_invitations)
        return teams

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_name'] = 'Zespoły z Twoich szkół'
        for team in context['teams']:
            if team.leader.recipient.filter(sender=self.guardian).filter(accepted=None).exists():
                team.invited = True
        return context
    
    def has_permission(self):
        if self.request.user.user_type == CustomUser.GUARDIAN:
            return True
        return False

@method_decorator(login_required, name='dispatch')
class InvitationCreateView(PermissionRequiredMixin, CreateView):
    http_method_names = ['post']
    model = Invitation

    fields = [
        'sender',
        'recipient',
    ]
    def post(self, request, *args, **kwargs):
        post_data = json.loads(request.body)
        recipient_id = post_data.get('id')
        if recipient_id and CustomUser.objects.filter(pk=recipient_id).exists():
            data = {
                "sender": request.user.id,
                "recipient": recipient_id,
            }
            FormClass = self.get_form_class()
            form = FormClass(data)
            if form.is_valid():
                if (not Invitation.accepted_none_objects.filter(sender=form.cleaned_data.get('sender')).filter(recipient=form.cleaned_data.get('recipient')).exists() and
                    not Invitation.accepted_none_objects.filter(sender=form.cleaned_data.get('recipient')).filter(recipient=form.cleaned_data.get('sender')).exists()):
                    form.save()
                    return JsonResponse({
                        'messageInvite': 'Zaproszony', 
                        'messageCancel': 'Anuluj',
                        'dataRecipientID': recipient_id,
                    })
        
        return HttpResponseBadRequest('Invalid request')
    
    def has_permission(self):
        user = self.request.user
        if user.user_type == CustomUser.GUARDIAN and user.schools.exists():
            return True
        if user.user_type == CustomUser.STUDENT and user.team_set.exists() and user.team_set.first().team_guardian is None:
            return True
        return False
    
@method_decorator(login_required, name='dispatch')
class InvitationCancelView(PermissionRequiredMixin, View):
    http_method_names = ['delete']
    model = Invitation

    def delete(self, request, *args, **kwargs):
        delete_data = json.loads(request.body)
        recipient_id = delete_data.get('id')
        if recipient_id and CustomUser.objects.filter(pk=recipient_id).exists():
            try:
                obj = self.model.accepted_none_objects.get(sender=request.user.id, recipient=recipient_id)
                obj.delete()
                return JsonResponse({'message': 'Zaproś', 'dataRecipientID': recipient_id})
            except self.model.DoesNotExist:
                return HttpResponseBadRequest('Invalid request')
    
    def has_permission(self):
        user = self.request.user
        if user.sender.filter(accepted=None).exists():
            return True
        return False
    
class InvitationListView(PermissionRequiredMixin, ListView):
    context_object_name = 'invitations'
    template_name = 'dashboard/invitations/list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_name'] = 'Aktywne zaproszenia'
        return context

    def get_queryset(self):
        return self.request.user.recipient.filter(accepted=None)
    
    def has_permission(self):
        return self.request.user.has_perm('dashboard.view_invitation')
    
class InvitationEditView(PermissionRequiredMixin, UpdateView):
    model = Invitation
    context_object_name = 'invitation'
    template_name = 'dashboard/invitations/edit.html'
    fields = [
        'accepted'
    ]

    def form_valid(self, form):
        if "accept" in self.kwargs:
            if self.kwargs["accept"]:
                self.object.accepted = True
                team_guardian = TeamGuardian()
                team_guardian.guardian = self.object.get_guardian()
                team_guardian.save()
                team = self.object.get_team()
                team.team_guardian = team_guardian
                team.save()
            else:
                self.object.accepted = False
            self.object.save()
        return HttpResponseRedirect(self.get_success_url())
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if "accept" in self.kwargs:
            accept = self.kwargs["accept"]
            context['accept'] = accept
            if accept:
                context['page_name'] = 'Zaakceptuj zaproszenie'
            else:
                context['page_name'] = 'Odrzuć zaproszenie'
        return context

    def has_permission(self):
        self.object = self.get_object()
        return self.object.recipient == self.request.user
    
    def get_success_url(self):
        if '_accept' in self.request.POST:
            if self.request.user.is_student():
                return reverse_lazy('dashboard:teams-detail', kwargs={'pk': self.request.user.team_set.first().id})
            
            if self.request.user.is_guardian():
                return reverse_lazy('dashboard:teams-guardian-list')
            
        if '_not-accept' in self.request.POST:
            return reverse_lazy('dashboard:invitations-list')

dashboard/templates/dashboard/teams/add.html
{% extends "dashboard/base.html" %}
{% block meta_title %}{{ page_name }} | Scolarctos{% endblock meta_title %}
{% block page_title %}{{ page_name }}{% endblock page_title %}
{% block breadcrumb %}
<li><span>{{ page_name }}</span></li>
{% endblock breadcrumb %}
{% block content %}
<div class="main-content-inner">
    <div class="row justify-content-md-center">
        <div class="col-lg-8 col-ml-10 col-sm-12">
            <div class="row">
                <!-- Textual inputs start -->
                <div class="col-12 mt-5">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="header-title">Nowy zespół</h4>
                            <div class="row">
                                <div class="col-lg-8 col-sm-12">
                                    <form method="post">
                                        {% csrf_token %}
                                        <div class="form-row">
                                            <div class="col-md-12 mb-3">
                                                <label for="{{ form.name.id_for_label }}" class="col-form-label">Nazwa zespołu</label>
                                                {{ form.name }}
                                                <div class="text-danger">{{ form.name.errors }}</div>
                                            </div>
                                        </div>
                                        <div class="form-row">
                                            <div class="col-md-12 mb-3">
                                                <label for="{{ form.school.id_for_label }}" class="col-form-label">Szkoła</label>
                                                {{ form.school }}
                                                <div class="text-danger">{{ form.school.errors }}</div>
                                                <div class="text-info">W przypadku braku Twojej szkoły na liście, pozostaw pole puste i zgłoś swoją szkolę przez formularz: <a href="{% url "dashboard:schools-new" %}">dodaj swoją szkołę</a></div>
                                            </div>
                                        </div>
                                        <div class="form-row">
                                            <div class="col-md-12 mb-3">
                                                <label for="{{ form.description.id_for_label }}" class="col-form-label">Opis</label>
                                                {{ form.description }}
                                                <div class="text-danger">{{ form.description.errors }}</div>
                                            </div>
                                        </div>
                                        <button type="submit" class="btn btn-primary mt-4 pr-4 pl-4" name="_save">Zapisz</button>
                                        <button type="submit" class="btn btn-primary mt-4 pr-4 pl-4 opacity-75" name="_continue">Zapisz i kontynuuj edycję</button>
                                        <a href="#" class="btn btn-warning mt-4 pr-4 pl-4" role="button" aria-pressed="true">Powrót</a>
                                    </form>
                                </div>
                                <div class="col-lg-4 col-sm-12">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Textual inputs end -->
            </div>
        </div>
    </div>
</div>    
{% endblock content %}

dashboard/templates/dashboard/teams/delete.html
{% extends "dashboard/base.html" %}
{% block meta_title %}{{ page_name }} | Scolarctos{% endblock meta_title %}
{% block page_title %}{{ page_name }}{% endblock page_title %}
{% block breadcrumb %}
{% if perms.dashboard.view_team %}<li><a href="{% url "dashboard:teams-list" %}">Zespoły</a></li>{% endif %}
<li><span>{{ page_name }}</span></li>
{% endblock breadcrumb %}
{% block content %}
<div class="main-content-inner">
    <div class="row justify-content-md-center">
        <div class="col-lg-6 col-ml-8 col-sm-12">
            <div class="row">
                <div class="mt-5">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="header-title text-center">Jesteś pewien?</h4>
                            <p class="text-center">Czy chcesz usunąć zespół: {{ team.name }}? Spowoduje to usunięcie wszystkich członków zespołu oraz dołączonych plików.</p>
                            <div class="mt-3 text-center">
                                <form method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-danger mt-4 pr-4 pl-4">Tak, na pewno</button>
                                    <a href="{% url "dashboard:teams-detail" team.id %}" class="btn btn-info mt-4 pr-4 pl-4" role="button" aria-pressed="true">Szczegóły zespołu</a>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>    
{% endblock content %}

dashboard/templates/dashboard/teams/list.html
{% extends "dashboard/base.html" %}
{% block meta_title %}{{ page_name }} | Scolarctos{% endblock meta_title %}
{% block page_title %}{{ page_name }}{% endblock page_title %}
{% block breadcrumb %}
<li><span>{{ page_name }}</span></li>
{% endblock breadcrumb %}
{% block content %}
        <div class="main-content-inner">
            <div class="row">
                <!-- Dark table start -->
                <div class="col-12 mt-5">
                    <div class="card">
                        <div class="card-body">
                            <div class="row mb-3">
                                <div class="col-lg-6">
                                    <h4 class="header-title">Lista zespołów</h4>
                                </div>
                                <div class="col-lg-6 d-flex justify-content-lg-end">
                                </div>
                            </div>
                            {% if teams %}
                            <div class="data-tables datatable-dark">
                                <table id="dataTableTeams" class="text-center">
                                    <thead class="">
                                        <tr>
                                            <th class="desktop">Nazwa</th>
                                            <th class="desktop">Szkoła</th>
                                            <th class="desktop">Kapitan</th>
                                            <th class="desktop">Opiekun</th>
                                            <th class="desktop">Potwierdzenie opiekuna</th>
                                            <th class="desktop">Zatwierdzony</th>
                                            <th class="desktop">Akcja</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for team in teams %}
                                        <tr>
                                            <td>{{ team.name }}</td>
                                            <td>
                                                {% if team.school %}
                                                <a class="d-inline-block text-truncate" href="{% url "dashboard:schools-detail" team.school.id %}" style="max-width: 220px;" title="{{ team.school.name }}">{{ team.school.name }}</a>
                                                {% else %}
                                                <span class="text-danger">Brak</span>
                                                {% endif %}
                                            </td>
                                            <td>
                                                {% if team.leader %}
                                                <a href="{% url "dashboard:users-detail" team.leader.id %}" title="{{ team.leader.first_name }} {{ team.leader.last_name }}">{{ team.leader.email }}</a>
                                                {% else %}
                                                <span class="text-danger">Brak</span>
                                                {% endif %}
                                            </td>                                            
                                            <td>
                                                {% if team.team_guardian %}
                                                <a href="{% url "dashboard:users-detail" team.team_guardian.guardian.id %}">{{ team.team_guardian.guardian.email }}</a>
                                                {% else %}
                                                <span class="text-danger">Brak</span>
                                                {% endif %}
                                            </td>
                                            <td>
                                                {% if team.team_guardian and team.team_guardian.confirmation %}
                                                <i title="Tak" class="fa fa-circle text-success"></i>
                                                {% else %}
                                                <i title="Nie" class="fa fa-circle text-danger"></i>
                                                {% endif %}
                                            </td>
                                            <td>
                                                {% if not team.editable %}
                                                <i title="Tak" class="fa fa-circle text-success"></i>
                                                {% else %}
                                                <i title="Nie" class="fa fa-circle text-danger"></i>
                                                {% endif %}
                                            </td>  
                                            <td>
                                                <div>
                                                    {% if perms.dashboard.view_team %}
                                                    <a href="{% url "dashboard:teams-detail" team.id %}" class="btn btn-info" role="button" aria-pressed="true">
                                                        <i class="ti-info"></i>
                                                    </a>
                                                    {% endif %}
                                                    {% if perms.dashboard.change_team %}
                                                    <a href="{% url "dashboard:teams-edit" team.id %}" class="btn btn-primary" role="button" aria-pressed="true">
                                                        <i class="ti-pencil-alt"></i>
                                                    </a>
                                                    {% endif %}
                                                    {% if perms.dashboard.delete_team %}
                                                    <a href="{% url "dashboard:teams-delete" team.id %}" class="btn btn-danger" role="button" aria-pressed="true">
                                                        <i class="ti-trash"></i>
                                                    </a>
                                                    {% endif %}
                                                </div>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            {% else %} 
                            <p class="text-danger">Lista zespołów jest pusta</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <!-- Dark table end -->
            </div>
        </div>
{% endblock content %}
{% block additionalthemecss %}
<!-- Start datatable css -->
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.18/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.jqueryui.min.css">
{% endblock additionalthemecss %}
{% block additionalthemescripts %}
<!-- Start datatable js -->
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
<script src="https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.18/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap.min.js"></script>
{% endblock additionalthemescripts %}