dashboard/urls.py
from django.urls import path

from .views import main, users, profile, schools, teams, invitations

app_name = 'dashboard'

urlpatterns = [
    path('', main.IndexView.as_view(), name='index'),
    path('users/admins/', users.UserAdminsListView.as_view(), name='users-list-admins'),
    path('users/admins/new/', users.CreateUserAdminView.as_view(), name='users-admins-new'),
    path('users/organizers/', users.UserOrganizersListView.as_view(), name='users-list-organizers'),
    path('users/organizers/new/', users.CreateUserOrganizerView.as_view(), name='users-organizers-new'),
    path('users/students/', users.UserStudentsListView.as_view(), name='users-list-students'),
    path('users/guardians/', users.UserGuardiansListView.as_view(), name='users-list-guardians'),
    path('users/<int:pk>/', users.UserDetailView.as_view(), name='users-detail'),
    path('users/<int:pk>/edit/', users.UserUpdateView.as_view(), name='users-edit'),
    path('users/<int:pk>/delete/', users.UserDeleteView.as_view(), name='users-delete'),
    path('profile/', profile.ProfileDetailView.as_view(), name='profile-detail'),
    path('profile/edit/', profile.ProfileUpdateView.as_view(), name='profile-edit'),
    path('profile/delete/', profile.ProfileDeleteView.as_view(), name='profile-delete'),
    path('schools/', schools.SchoolsListView.as_view(), name='schools-list'),
    path('schools/type/<int:type>/', schools.SchoolsListView.as_view(), name='schools-list-type'),
    path('schools/my-schools/', schools.SchoolsGuardianListView.as_view(), name='schools-guardian-list'),
    path('schools/my-schools/edit/', schools.SchoolsGuardianUpdateView.as_view(), name='schools-guardian-edit'),
    path('schools/new/', schools.SchoolsCreateView.as_view(), name='schools-new'),
    path('schools/<int:pk>/', schools.SchoolsDetailView.as_view(), name='schools-detail'),
    path('schools/<int:pk>/edit/', schools.SchoolsUpdateView.as_view(), name='schools-edit'),
    path('schools/<int:pk>/delete/', schools.SchoolsDeleteView.as_view(), name='schools-delete'),
    path('teams/', teams.TeamsListView.as_view(), name='teams-list'),
    path('teams/new/', teams.TeamsCreateView.as_view(), name='teams-new'),
    path('teams/<int:pk>/', teams.TeamsDetailView.as_view(), name='teams-detail'),
    path('teams/<int:pk>/edit/', teams.TeamsUpdateView.as_view(), name='teams-edit'),
    path('teams/<int:pk>/delete/', teams.TeamsDeleteView.as_view(), name='teams-delete'),
    path('teams/<int:pk>/leader/add/', teams.TeamsLeaderConnectView.as_view(), name='teams-leader-new'),
    path('teams/<int:team_id>/leader/<int:pk>/edit/', teams.TeamsLeaderUpdateView.as_view(), name='teams-leader-edit'),
    path('teams/<int:pk>/leader/delete/', teams.TeamsLeaderDisconnectView.as_view(), name='teams-leader-delete'),
    path('teams/<int:pk>/members/new/', teams.TeamsMembersCreateView.as_view(), name='teams-members-new'),
    path('teams/members/<int:pk>/edit/', teams.TeamsMembersUpdateView.as_view(), name='teams-members-edit'),
    path('teams/members/<int:pk>/delete/', teams.TeamsMembersDeleteView.as_view(), name='teams-members-delete'),
    path('teams/<int:team_id>/file/<int:pk>/delete/', teams.TeamsFileDeleteView.as_view(), name='teams-file-delete'),
    path('teams/my/', teams.TeamsGuardianView.as_view(), name='teams-guardian-list'),
    path('teams/<int:pk>/disconnect/', teams.TeamsGuardianDisconnectView.as_view(), name='teams-guardian-disconnect'),
    path('invitations/', invitations.InvitationListView.as_view(), name='invitations-list'),
    path('invitations/<int:pk>/accept/', invitations.InvitationEditView.as_view(), name='invitations-edit-accept', kwargs={'accept': True}),
    path('invitations/<int:pk>/not-accept/', invitations.InvitationEditView.as_view(), name='invitations-edit-not-accept',  kwargs={'accept': False}),
    path('invitations/available-guardians/', invitations.InvitationsAvailableGuardiansListView.as_view(), name='invitations-available-guardians-list'),
    path('invitations/available-teams/', invitations.InvitationsAvailableTeamsListView.as_view(), name='invitations-available-teams-list'),
    path('invitations/invite/', invitations.InvitationCreateView.as_view(), name='invitations-invite'),
    path('invitations/invite-cancel/', invitations.InvitationCancelView.as_view(), name='invitations-invite-cancel'),
]

scolarctosapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('dashboard/', include('dashboard.urls')),
]

handler403 = 'dashboard.views.main.error_403'

dashboard/models/invitation.py
from django.db import models
from django.utils import timezone
from users.models import CustomUser as User
from dashboard.validators import validate_student_guardian

class InvitationNoneAcceptedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(accepted__isnull=True)
    
class Invitation(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender', validators=[validate_student_guardian])
    recipient = models.ForeignKey(User, on_delete=models.CASCADE, related_name='recipient', validators=[validate_student_guardian])
    accepted = models.BooleanField(blank=True, null=True, default=None) 
    created = models.DateField(default=timezone.now)

    objects = models.Manager()
    accepted_none_objects = InvitationNoneAcceptedManager()

    def __str__(self):
        return f'From: {self.sender.email} | To: {self.recipient.email} | Accepted: {self.accepted}'
    
    def get_guardian(self):
        if self.sender.is_guardian():
            return self.sender
        elif self.recipient.is_guardian():
            return self.recipient
    
    def get_student(self):
        if self.sender.is_student():
            return self.sender
        elif self.recipient.is_student():
            return self.recipient

    def get_team(self):
        leader = self.get_student()
        return leader.team_set.first()

dashboard/models/school.py
from django.db import models
from django.core.validators import MinLengthValidator, RegexValidator
from django.utils import timezone
from users.models import CustomUser as User

class School(models.Model):
    FIRST_LEVEL = 1
    SECOND_LEVEL = 2

    SCHOOL_TYPE_CHOICES = (
        (FIRST_LEVEL, 'Podstawowa'),
        (SECOND_LEVEL, 'Ponadpodstawowa'),
    )

    name = models.CharField(max_length=255, unique=True)
    street = models.CharField(max_length=63)
    postcode = models.CharField(max_length=6, validators=[MinLengthValidator(6), RegexValidator(
                regex=r'^\d{2}-\d{3}$',
                message="Wprowadź prawidłowy kod pocztowy w formacie 12-345",
            ),])
    city = models.CharField(max_length=63)
    school_type = models.PositiveSmallIntegerField(choices=SCHOOL_TYPE_CHOICES, default=FIRST_LEVEL)
    accepted = models.BooleanField(default=False)
    added_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    added_date = models.DateTimeField(default=timezone.now)
    guardians = models.ManyToManyField(
        User, 
        null=True, 
        blank=True, 
        related_name="schools", 
        related_query_name="guardians",
        )

    def __str__(self):
        return f'Name: {self.name} | Street: {self.street} | Postcode: {self.postcode} | City: {self.city} | Type: {self.school_type} | Accepted: {self.accepted} | Date: {self.added_date}'
    

dashboard/models/team.py
import os
from django.db import models
from django.utils import timezone
from users.models import CustomUser as User
from dashboard.models.school import School
from dashboard.models.team_guardian import TeamGuardian
from files.models import File

class Team(models.Model):
    MAX_MEMBERS = 3
    MAX_FILES = 5

    name = models.CharField(max_length=63, unique=True)
    description = models.TextField(blank=True)
    leader = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    team_guardian = models.ForeignKey(TeamGuardian, on_delete=models.SET_NULL, null=True, blank=True)
    team_members = models.ManyToManyField(
        User, 
        null=True, 
        blank=True, 
        related_name="team_members", 
        related_query_name="team_member",
        )
    school = models.ForeignKey(School, on_delete=models.SET_NULL, null=True, blank=True)
    editable = models.BooleanField(default=True)
    files = models.ManyToManyField(
        File, 
        null=True, 
        blank=True, 
        related_name="teams",
    )
    added_date = models.DateField(default=timezone.now)

    def __str__(self):
        return f'Name: {self.name} | Desc: {self.description} | Leader: {self.leader} | Guardian: {self.team_guardian} | School: {self.school} | Date: {self.added_date}'
    
    def delete(self, **kwargs):
        self.team_members.all().delete()
        # Must delete each file separately
        if self.files.exists():
            first_file = self.files.first()
            files_dir = first_file.path.path
            files_dir = files_dir.replace(first_file.name, '')
            for file in self.files.all():
                file.delete()
            os.rmdir(files_dir)
        return super().delete(**kwargs)

dashboard/models/team_guardian.py
from django.db import models
from users.models import CustomUser as User
from files.models import File

class TeamGuardian(models.Model):
    guardian = models.ForeignKey(User, on_delete=models.CASCADE)
    confirmation = models.BooleanField(default=False)
    confirmation_file = models.ForeignKey(File, on_delete=models.SET_NULL, null=True, blank=True)
    
    def __str__(self):
        return f'Guardian: {self.guardian} | Confirmation status: {self.confirmation} | Confirmation file: {self.confirmation_file}'

dashboard/models/team_tutor.py
from django.db import models
from users.models import CustomUser as User
from files.models import File

class TeamTutor(models.Model):
    tutor = models.ForeignKey(User, on_delete=models.CASCADE)
    confirmation = models.BooleanField(default=False)
    confirmation_file = models.ForeignKey(File, on_delete=models.CASCADE, null=True, blank=True)
    
    def __str__(self):
        return f'Tutor: {self.tutor} | Confirmation status: {self.confirmation} | Confirmation file: {self.confirmation_file}'

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.core.validators import MinLengthValidator
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from .managers import CustomUserManager
from gdpr.models import Gdpr

class CustomUser(AbstractBaseUser, PermissionsMixin):
    STUDENT = 1
    STUDENT_TEAM_MEMBER = 11
    GUARDIAN = 2
    ORGANIZER = 3
    ADMIN = 4

    USER_TYPE_CHOICES = (
        (STUDENT, 'Uczeń'),
        (GUARDIAN, 'Opiekun'),
        (ORGANIZER, 'Organizator'),
        (ADMIN, 'Administrator'),
    )

    email = models.EmailField(_("email address"), unique=True)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=9, validators=[MinLengthValidator(9)], unique=True, null=True, default=None, blank=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)
    user_type = models.PositiveSmallIntegerField(choices=USER_TYPE_CHOICES, default=STUDENT)
    gdpr = models.OneToOneField(Gdpr, null=True, blank=True, on_delete=models.CASCADE, related_name='gdpr')

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email
    
    def is_student(self):
        return self.user_type == self.STUDENT
    
    def is_guardian(self):
        return self.user_type == self.GUARDIAN
    
    class Meta:
        verbose_name = _("user")
        verbose_name_plural = _("users")
        permissions = [
            ("add_admins", "Can add admins"),
            ("change_admins", "Can change admins"),
            ("delete_admins", "Can delete admins"),
            ("view_admins", "Can view admins"),
            ("add_organizers", "Can add organizers"),
            ("change_organizers", "Can change organizers"),
            ("delete_organizers", "Can delete organizers"),
            ("view_organizers", "Can view organizers"),
        ]

class CustomGroup():
    names = {
        CustomUser.STUDENT: "Students",
        CustomUser.GUARDIAN: "Guardians",
        CustomUser.ORGANIZER: "Organizers",
        CustomUser.ADMIN: "Admins",
    }

dashboard/views/profile.py
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.views.generic.edit import DeleteView, UpdateView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import PermissionRequiredMixin
from users.models import CustomUser
from authentication.forms import ConfirmationForm
from authentication.utils import  send_confirmation_code_mail, generate_confirmation_code

'''
### Profile Views
'''
@method_decorator(login_required, name='dispatch')
class ProfileDetailView(PermissionRequiredMixin, DetailView):
    model = CustomUser
    context_object_name = 'user'
    template_name = 'dashboard/profile/detail.html'

    def get_object(self):
        return self.model.objects.get(pk=self.request.user.id)

    def get_context_data(self, **kwargs):
        context = super(ProfileDetailView, self).get_context_data(**kwargs)
        context['page_name'] = f"Profil: {context['user'].first_name} {context['user'].last_name}"
        context['user'].user_type_name = context['user'].USER_TYPE_CHOICES[context['user'].user_type - 1][1]
        return context
    
    def has_permission(self):
        context_user_object = self.get_object()
        if context_user_object.id == self.request.user.id:
            return True
        
@method_decorator(login_required, name='dispatch')
class ProfileUpdateView(PermissionRequiredMixin, UpdateView):
    model = CustomUser
    context_object_name = 'user'
    template_name = 'dashboard/profile/edit.html'

    fields = [ 
        'first_name', 
        'last_name',
        'phone_number',
        'description',
    ]

    def get_object(self):
        return self.model.objects.get(pk=self.request.user.id)

    def get_context_data(self, **kwargs):
        context = super(ProfileUpdateView, self).get_context_data(**kwargs)
        context['page_name'] = "Edytuj swój profil"
        for field in self.fields:
            context['form'].fields[field].widget.attrs['class'] = 'form-control'
        return context
    
    def has_permission(self):
        context_user_object = self.get_object()
        if context_user_object.id == self.request.user.id:
            return True
    
    def get_success_url(self) -> str:
        if '_save' in self.request.POST:
            return reverse_lazy('dashboard:profile-detail')
        elif '_continue' in self.request.POST:
            return reverse_lazy('dashboard:profile-edit')

@method_decorator(login_required, name='dispatch')
class ProfileDeleteView(PermissionRequiredMixin, DeleteView):
    model = CustomUser
    context_object_name = 'user'
    template_name = 'dashboard/profile/delete.html'
    form_class = ConfirmationForm
    confirmation_code = generate_confirmation_code()

    def get_object(self):
        return self.model.objects.get(pk=self.request.user.id)
    
    def dispatch(self, request, *args, **kwargs):
        messages_storage = messages.get_messages(self.request)
        if request.method == 'GET' and not messages_storage:
            send_confirmation_code_mail(to_user=self.request.user, confirmation_code=self.confirmation_code)
        return super(ProfileDeleteView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ProfileDeleteView, self).get_context_data(**kwargs)
        context['page_name'] = "Usuwanie konta"
        return context
    
    def has_permission(self):
        context_user_object = self.get_object()
        if context_user_object.id == self.request.user.id:
            return True
    
    def get_success_url(self) -> str:
        return reverse_lazy('logout')
    
    def form_valid(self, form):
        form_confirm_code = form.cleaned_data['confirm_code']
        if self.confirmation_code == form_confirm_code:
            success_url = self.get_success_url()
            self.object.delete()
            return HttpResponseRedirect(success_url)
        else:
            messages.add_message(self.request, messages.ERROR, f'Kod potwierdzający: {form_confirm_code} jest nieprawidłowy')
            return HttpResponseRedirect(reverse_lazy('dashboard:profile-delete'))

dashboard/templates/dashboard/common/header.html
<!-- header area start -->
<div class="header-area">
    <div class="row align-items-center">
        <!-- nav and search button -->
        <div class="col-md-6 col-sm-8 clearfix">
            <div class="nav-btn pull-left">
                <span></span>
                <span></span>
                <span></span>
            </div>
            <div class="search-box pull-left">
                <form action="#">
                    <input type="text" name="search" placeholder="Search..." required>
                    <i class="ti-search"></i>
                </form>
            </div>
        </div>
        <!-- profile info & task notification -->
        <div class="col-md-6 col-sm-4 clearfix">
            <ul class="notification-area pull-right">
                <li id="full-view"><i class="ti-fullscreen"></i></li>
                <li id="full-view-exit"><i class="ti-zoom-out"></i></li>
                <li class="dropdown">
                    <i class="ti-bell dropdown-toggle" data-toggle="dropdown">
                        <span>2</span>
                    </i>
                    <div class="dropdown-menu bell-notify-box notify-box">
                        <span class="notify-title">You have 3 new notifications <a href="#">view all</a></span>
                        <div class="nofity-list">
                            <a href="#" class="notify-item">
                                <div class="notify-thumb"><i class="ti-key btn-danger"></i></div>
                                <div class="notify-text">
                                    <p>You have Changed Your Password</p>
                                    <span>Just Now</span>
                                </div>
                            </a>
                            <a href="#" class="notify-item">
                                <div class="notify-thumb"><i class="ti-comments-smiley btn-info"></i></div>
                                <div class="notify-text">
                                    <p>New Commetns On Post</p>
                                    <span>30 Seconds ago</span>
                                </div>
                            </a>
                            <a href="#" class="notify-item">
                                <div class="notify-thumb"><i class="ti-key btn-primary"></i></div>
                                <div class="notify-text">
                                    <p>Some special like you</p>
                                    <span>Just Now</span>
                                </div>
                            </a>
                            <a href="#" class="notify-item">
                                <div class="notify-thumb"><i class="ti-comments-smiley btn-info"></i></div>
                                <div class="notify-text">
                                    <p>New Commetns On Post</p>
                                    <span>30 Seconds ago</span>
                                </div>
                            </a>
                            <a href="#" class="notify-item">
                                <div class="notify-thumb"><i class="ti-key btn-primary"></i></div>
                                <div class="notify-text">
                                    <p>Some special like you</p>
                                    <span>Just Now</span>
                                </div>
                            </a>
                            <a href="#" class="notify-item">
                                <div class="notify-thumb"><i class="ti-key btn-danger"></i></div>
                                <div class="notify-text">
                                    <p>You have Changed Your Password</p>
                                    <span>Just Now</span>
                                </div>
                            </a>
                            <a href="#" class="notify-item">
                                <div class="notify-thumb"><i class="ti-key btn-danger"></i></div>
                                <div class="notify-text">
                                    <p>You have Changed Your Password</p>
                                    <span>Just Now</span>
                                </div>
                            </a>
                        </div>
                    </div>
                </li>
                <li class="dropdown">
                    <i class="fa fa-envelope-o dropdown-toggle" data-toggle="dropdown"><span>3</span></i>
                    <div class="dropdown-menu notify-box nt-enveloper-box">
                        <span class="notify-title">You have 3 new notifications <a href="#">view all</a></span>
                        <div class="nofity-list">
                            <a href="#" class="notify-item">
                                <div class="notify-thumb">
                                    <i class="ti-email btn-info"></i>
                                </div>
                                <div class="notify-text">
                                    <p>Aglae Mayer</p>
                                    <span class="msg">Hey I am waiting for you...</span>
                                    <span>3:15 PM</span>
                                </div>
                            </a>
                            <a href="#" class="notify-item">
                                <div class="notify-thumb">
                                    <i class="ti-email btn-info"></i>
                                </div>
                                <div class="notify-text">
                                    <p>Aglae Mayer</p>
                                    <span class="msg">When you can connect with me...</span>
                                    <span>3:15 PM</span>
                                </div>
                            </a>
                            <a href="#" class="notify-item">
                                <div class="notify-thumb">
                                    <i class="ti-email btn-info"></i>
                                </div>
                                <div class="notify-text">
                                    <p>Aglae Mayer</p>
                                    <span class="msg">I missed you so much...</span>
                                    <span>3:15 PM</span>
                                </div>
                            </a>
                        </div>
                    </div>
                </li>
                <li class="settings-btn">
                    <i class="ti-settings"></i>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- header area end -->

dashboard/templates/dashboard/common/sidebar-menu.html
{% load static %}
<!-- sidebar menu area start -->
<div class="sidebar-menu">
    <div class="sidebar-header">
        <div class="logo">
            <a href="{% url "dashboard:index" %}"><img src="{% static "assets/images/custom/scolarctos-logo.png" %}" alt="logo"></a>
        </div>
    </div>
    <div class="main-menu">
        <div class="menu-inner">
            <nav>
                <ul class="metismenu" id="menu">
                    <li class="{% if request.resolver_match.url_name == "index" %}active{% endif %}"><a href="{% url "dashboard:index" %}"><i class="ti-dashboard"></i> <span>Panel</span></a></li>
                    {% if perms.users.view_admins or perms.users.view_organizers or perms.users.view_customuser %}
                    <li>
                        <a href="javascript:void(0)" aria-expanded="true"><i class="ti-user"></i><span>Użytkownicy</span></a>
                        <ul class="collapse">
                            {% if perms.users.view_admins %}
                            <li class="{% if request.resolver_match.url_name == "users-list-admins" %}active{% endif %}"><a href="{% url "dashboard:users-list-admins" %}">Administratorzy</a></li>
                            {% endif %}
                            {% if perms.users.view_organizers %}
                            <li class="{% if request.resolver_match.url_name == "users-list-organizers" %}active{% endif %}"><a href="{% url "dashboard:users-list-organizers" %}">Organizatorzy</a></li>
                            {% endif %}                            
                            {% if perms.users.view_customuser %}
                            <li class="{% if request.resolver_match.url_name == "users-list-students" %}active{% endif %}"><a href="{% url "dashboard:users-list-students" %}">Uczniowie</a></li>                            
                            <li class="{% if request.resolver_match.url_name == "users-list-guardians" %}active{% endif %}"><a href="{% url "dashboard:users-list-guardians" %}">Opiekunowie</a></li>                            
                            {% endif %}
                        </ul>
                    </li>
                    {% endif %}
                    {% if perms.dashboard.view_school %}
                    <li>
                        <a href="javascript:void(0)" aria-expanded="true"><i class="ti-ruler-pencil"></i><span>Szkoły</span></a>
                        <ul class="collapse">
                            <li class="{% if request.resolver_match.url_name == "schools-list" %}active{% endif %}"><a href="{% url "dashboard:schools-list" %}">Wszystkie</a></li>
                            <li class="{% if request.resolver_match.url_name == "schools-list-type" and school_type == 1 %}active{% endif %}"><a href="{% url "dashboard:schools-list-type" 1 %}">Podstawowe</a></li>
                            <li class="{% if request.resolver_match.url_name == "schools-list-type" and school_type == 2 %}active{% endif %}"><a href="{% url "dashboard:schools-list-type" 2 %}">Ponadpodstawowe</a></li>
                            {% if user.user_type == user.GUARDIAN %}
                            <li class="{% if request.resolver_match.url_name == "schools-guardian-list" %}active{% endif %}"><a href="{% url "dashboard:schools-guardian-list" %}">Moje szkoły</a></li> 
                            {% endif %}
                            {% if perms.dashboard.add_school %}
                            <li class="{% if request.resolver_match.url_name == "schools-new" %}active{% endif %}"><a href="{% url "dashboard:schools-new" %}">Dodaj</a></li>
                            {% endif %}                            
                        </ul>
                    </li>
                    {% endif %}
                    <li>
                        <a href="javascript:void(0)" aria-expanded="true"><i class="fa fa-users"></i><span>Zespoły</span></a>
                        <ul class="collapse">
                            {% with team=user.team_set.first %}
                                {% if team %}
                                <li><a class="{% if request.resolver_match.url_name == "teams-detail" %}active{% endif %}" href="{% url "dashboard:teams-detail" team.id %}">Mój zespół</a></li>
                                    {% if not team.team_guardian %}
                                    <li><a href="#" aria-expanded="true">Zaproszenia</a>
                                        <ul class="collapse">
                                            <li class="{% if request.resolver_match.url_name == "invitations-list" %}active{% endif %}"><a href="{% url "dashboard:invitations-list" %}">Otrzymane</a></li>
                                            <li><a class="{% if request.resolver_match.url_name == "invitations-available-guardians-list" %}active{% endif %}" href="{% url "dashboard:invitations-available-guardians-list" %}">Zaproś opiekuna</a></li>
                                        </ul>
                                    </li>
                                    {% endif %}
                                {% elif perms.dashboard.add_team %}
                                <li><a class="{% if request.resolver_match.url_name == "teams-new" %}active{% endif %}" href="{% url "dashboard:teams-new" %}">Utwórz zespół</a></li>
                                {% endif %}

                            {% endwith %}
                            {% if user.user_type == user.GUARDIAN %}
                            <li><a class="{% if request.resolver_match.url_name == "teams-guardian-list" %}active{% endif %}" href="{% url "dashboard:teams-guardian-list" %}">Moje zespoły</a></li>
                            <li><a href="#" aria-expanded="true">Zaproszenia</a>
                                <ul class="collapse">
                                    <li class="{% if request.resolver_match.url_name == "invitations-list" %}active{% endif %}"><a href="{% url "dashboard:invitations-list" %}">Otrzymane</a></li>
                                    <li class="{% if request.resolver_match.url_name == "invitations-available-teams-list" %}active{% endif %}"><a href="{% url "dashboard:invitations-available-teams-list" %}">Zaproś zespół</a></li>
                                </ul>
                            </li>
                            {% endif %}
                            {% if perms.dashboard.view_team %}
                                <li class="{% if request.resolver_match.url_name == "teams-list" %}active{% endif %}"><a href="{% url "dashboard:teams-list" %}">Wszystkie</a></li>
                            {% endif %}
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</div>
<!-- sidebar menu area end -->